openapi: 3.0.0
info:
  title: 가구 쇼핑몰 API
  version: 0.0.1
  description: 가구 쇼핑몰 애플리케이션을 위한 API

servers:
  - url: https://api.furnitureshop.com/v1

paths:
  /users:
    get:
      summary: 모든 사용자 목록 조회
      description: 관리자용 API로, 모든 사용자의 목록을 반환합니다.
      tags:
        - 사용자
      responses:
        '200':
          description: 성공적인 응답
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      security:
        - BearerAuth: []
    post:
      summary: 새 사용자 등록
      description: 새로운 사용자를 시스템에 등록합니다.
      tags:
        - 사용자
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '201':
          description: 사용자가 성공적으로 생성됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users/{id}:
    get:
      summary: 특정 사용자 정보 조회
      description: 주어진 ID에 해당하는 사용자의 정보를 조회합니다.
      tags:
        - 사용자
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 성공적인 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
        - BearerAuth: []
    put:
      summary: 사용자 정보 수정
      description: 주어진 ID에 해당하는 사용자의 정보를 수정합니다.
      tags:
        - 사용자
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
      responses:
        '200':
          description: 사용자 정보가 성공적으로 수정됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
        - BearerAuth: []

  /products:
    get:
      summary: 상품 목록 조회
      description: 모든 상품의 목록을 반환합니다. 페이지네이션을 지원합니다.
      tags:
        - 상품
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 성공적인 응답
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: 새 상품 등록
      description: 새로운 상품을 시스템에 등록합니다. 관리자 권한이 필요합니다.
      tags:
        - 상품
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '201':
          description: 상품이 성공적으로 등록됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
      security:
        - BearerAuth: []

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time
    NewUser:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    UpdateUser:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
    Product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: integer
    NewProduct:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: integer

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer